INFO:__main__:Loaded model_type: /mnt/file2/changye/model/NLP/Qwen2.5-1.5B-Instruct
Traceback (most recent call last):
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/train.py", line 145, in <module>
    main()
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/train.py", line 64, in main
    dataset = load_data(args.train_dataset, args.val_dataset)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/supervised_dataset.py", line 18, in load_data
    train_data = Dataset.from_json(train_path)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1184, in from_json
    return JsonDatasetReader(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/io/json.py", line 40, in __init__
    self.builder = Json(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/builder.py", line 360, in __init__
    data_files = DataFilesDict.from_patterns(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 721, in from_patterns
    else DataFilesList.from_patterns(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 624, in from_patterns
    resolve_pattern(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 411, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/mnt/file2/changye/dataset/NLP/casual_formal_pair_ACL40k/train'
Traceback (most recent call last):
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/train.py", line 145, in <module>
    main()
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/train.py", line 64, in main
    dataset = load_data(args.train_dataset, args.val_dataset)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning_deepspeed/supervised_dataset.py", line 18, in load_data
    train_data = Dataset.from_json(train_path)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1184, in from_json
    return JsonDatasetReader(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/io/json.py", line 40, in __init__
    self.builder = Json(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/builder.py", line 360, in __init__
    data_files = DataFilesDict.from_patterns(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 721, in from_patterns
    else DataFilesList.from_patterns(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 624, in from_patterns
    resolve_pattern(
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/data_files.py", line 411, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/mnt/file2/changye/dataset/NLP/casual_formal_pair_ACL40k/train'
